language: python
  - "2.7"
sudo: required
services:
  - docker
script:
  - docker pull mattkomm/cvmfs-cms
  - echo $PWD
  - ls
  - ls test
  - docker run -h dev --privileged -v $PWD:/scripts mattkomm/cvmfs-cms /bin/bash -c /scripts/test/runCMSSWTest.sh
