language: python
  - "2.7"
sudo: required
services:
  - docker
script:
  - docker run --rm --privileged -v $PWD/scripts:ro --device /dev/fuse clelange/slc6-cmssw-cvmfs /bin/bash -c test/runCMSSWTest.sh
